name: Test

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/deploy.yml"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up SDL
      run: sudo apt install libsdl2{,-image,-mixer,-ttf,-gfx}-dev

    - name: Go tidy
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
